version: '3'
services:

  webserver:
    depends_on:
      - kafka
    build: .
    ports:
      - "8000:8000"
    command: >
      /run_class.sh -DKAFKA_HOST=kafka org.exaspace.kafkawait.demo.CalculatorWebServer

  calculator:
    depends_on:
      - kafka
    build: .
    environment:
      KAFKA_HOST: kafka
    command: >
      /run_class.sh -DKAFKA_HOST=kafka org.exaspace.kafkawait.demo.CalculatorEventProcessor

  kafka:
    hostname: kafka
    image: docker.io/bitnami/kafka:3.3
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  zookeeper:
     image: docker.io/bitnami/zookeeper:3.8
     ports:
       - '2181:2181'
     environment:
       - ALLOW_ANONYMOUS_LOGIN=yes
